name: "IPTV Channels Bot"

on:
  push:
    branches:
      - main
  schedule:
    - cron: 00 02 * * 0

jobs:
  feed-processor:
    name: IPTV Channels fetch processor
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Build JSON
        run: node index.js
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
